from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas
from datetime import datetime


def create_report(student_name, major):

    filename = "FuturePath_Report.pdf"

    pdfmetrics.registerFont(
        TTFont(
            "Arabic",
            "assets/fonts/NotoSansArabic-Regular.ttf"
        )
    )

    pdf = canvas.Canvas(filename)

    # عنوان التقرير
    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawString(
        180,
        800,
        "FuturePath AI Report"
    )

    # خط فاصل
    pdf.line(
        50,
        780,
        550,
        780
    )

    # بيانات الطالب
    pdf.setFont(
        "Helvetica",
        14
    )

    pdf.drawString(
        70,
        730,
        f"Student Name: {student_name}"
    )

    pdf.drawString(
        70,
        690,
        f"Recommended Major: {major}"
    )

    pdf.drawString(
        70,
        650,
        f"Report Date: {datetime.now().strftime('%Y-%m-%d')}"
    )

    # ملاحظة
    pdf.setFont(
        "Helvetica-Oblique",
        12
    )

    pdf.drawString(
        70,
        580,
        "Generated by FuturePath AI Career Guidance Platform"
    )

    pdf.save()

    return filename